name       : microdns
version    : 0.1.2
release    : 2
source     :
    - https://github.com/videolabs/libmicrodns/releases/download/0.1.2/microdns-0.1.2.tar.xz : 666c4b9d86b5b3c37357bb78453c7e8b72cd65ade22d0a7963bfbefe51509b5c
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Minimal mDNS resolver (and announcer) library
description: |
    Minimal mDNS resolver (and announcer) library
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
