name       : microdns
version    : 0.0.8
release    : 1
source     :
    - https://download.videolan.org/contrib/microdns/microdns-0.0.8.tar.gz : 4ffbc5d9f28edfaab475112b97c6ca650261541a926b69781626661ae736fe53
license    : LGPL-2.1
component  : programming.library
summary    : Minimal mDNS resolver (and announcer) library
description: |
    Minimal mDNS resolver (and announcer) library
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
