name       : microdns
version    : 0.2.0
release    : 3
source     :
    - https://github.com/videolabs/libmicrodns/releases/download/0.2.0/microdns-0.2.0.tar.xz : 2da28e7dda4861d76f797f92ac3e6c3e048333b95f9e4fc3a6548ad8afd8c446
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Minimal mDNS resolver (and announcer) library
description: |
    Minimal mDNS resolver (and announcer) library
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
